version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PORT=8080
      - GRPC_SERVER_URL=internal-service:50051
    depends_on:
      - internal-service

  internal-service:
    build:
      context: .
      dockerfile: ./internal-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - APP_ENV=development
      - PORT=50051
      - DB_URL=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: